# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn test allure:report
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/testng/
            find . -type f -regex ".*/target/surefire-reports/TEST-TestSuite.xml" -exec cp {} ~/test-results/testng/ \;
          when: always
      - store_artifacts:
          path: target/surefire-reports/html
          destination: HTML report

    docker:
      - image: cimg/openjdk:18.0
workflows:

  welcome:

    jobs:
      - test