version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:18.0

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Set up JDK 18
          command: |
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-18.0.1/bin/java 1
            sudo update-alternatives --set java /usr/lib/jvm/jdk-18.0.1/bin/java

      - run:
          name: Build and test
          command: mvn clean test

      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: target/surefire-reports
          destination: surefire-reports

      - store_artifacts:
          path: target/allure-results
          destination: allure-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
